### ISSUE TITLE
Support for active/inactive status

### ISSUE THREAD

**Issue by Evidlo** [acm-uiuc/groot-groups-store#48]
A lot of the SIGs are not active, which is not reflected on the SIG page.  There should probably be a `status` string field which shows which SIGs are still running.

**Comment by narendasan** [comment]
Typically when a SIG goes defunct we (meaning Top4) remove them from the yaml. Easier to do that than add a new field. Then only active sigs are in the file but we still have a backup in the git history.

**Comment by rauhul** [comment]
closed by #50

**Comment by Evidlo** [comment]
I noticed these changes are still not showing up at https://acm.illinois.edu/sigs

**Comment by narendasan** [comment]
@aashishkapur or @bcongdon can you redeploy?
